### PR TITLE
Add LMPOP

### PR DESCRIPTION
**Pull request by Palladinium**
Currently failing due to needing redis-rb v5 (see also #281 and #293)

### CODE REVIEW

**Comment by Palladinium** [comment]
I'll wait a week or two to see if #293 progresses, if not I'll take a stab at updating to v5 from scratch myself

**Comment by sds** [comment]
Shout out to @hieuk09 who submitted support for `redis-rb` v5 in #314.

You should be able to pick this up again after a rebase.

**Comment by Palladinium** [comment]
A bunch of tests fail on my local environment, and also a bunch of CI checks fail too. They all seem unrelated to the LMPOP changes, so I'm not sure what's up. Do you have any ideas?

**Comment by sds** [comment]
@Palladinium the tests I see failing are all on Redis 6.2 and mention `lmpop`, so they seem relevant?

Lastly, the Overcommit failure seems like it would be solved by adding `base64` to the gemspec.

**Comment by Palladinium** [comment]
Ah of course, LMPOP was only introduced in Redis v7, so those failures make sense

**Comment by sds** [comment]
Sorry, I forgot `lmpop` is new as of Redis 7. Can you update the tests to be skipped for Redis 6.2?

**Comment by sds** [comment]
Thank you for the quick turnaround! Released in [0.48.0](https://github.com/sds/mock_redis/releases/tag/v0.48.0)

**Pull request merged**
